### ISSUE TITLE
Expired Discord link

### ISSUE THREAD

**Issue by tadasant** [OpenDataMCP/OpenDataMCP#7]
Hi team! I'd love to join the Discord on your README:

> We want to build a helping community around the challenge of bringing open data to LLM's. Join us on discord to start chatting: https://discord.gg/QPFFZWKW

But I'm hitting this:

![CleanShot 2024-12-20 at 12 31 20](https://github.com/user-attachments/assets/075665d4-3912-4230-8f48-5cbcd2a95482)

**Comment by grll** [comment]
Hi @tadasant, thanks for your interest in the project: https://discord.gg/hDg4ZExjGs this one should work. It's not very active at the moment but happy to chat!
